### ISSUE TITLE
Day- & Night-Profile

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#20]
Automatic activation of day and night profiles during on-call state.
For example:
- Internet on/off => unfortunately not allowed anymore
- Volume level => done

**Comment by bakito** [comment]
These would be nice too

- mobile data on/off
- profiles with from/to

**Comment by bakito** [comment]
Unfortunately toggling mobile data is not allowed. 
https://github.com/renyuneyun/Easer/issues/118#issuecomment-425346319

**Comment by frimtec** [comment]
Bad news :-(

**Comment by frimtec** [comment]
Hint to change WIFI state: https://stackoverflow.com/questions/8863509/how-to-programmatically-turn-off-wifi-on-android-device

**Comment by frimtec** [comment]
Arrg, Android Q also disallows to enable/disable wifi state :-(
