### ISSUE TITLE
PagerDuty support ?

### ISSUE THREAD

**Issue by gled-rs** [frimtec/pikett-assist#582]
Hi,

I was looking at augmenting my pagerduty experience and Passist looked like a super good fit, but I can't find if it is able to extract the proper ack reply from the text of the alert.

PagerDuty asks for a number sent with the alert to be sent back to ACK alerts. It should be doable to extract with a regular expression. Happy to help debug if you want !

**Comment by frimtec** [comment]
Hi
Currently only static reply SMS are possible for acks.
But sure, it should be no problem to generate dynamic replies based on the received SMS. 
Can you send me some example messages and the expected replies?

**Comment by frimtec** [comment]
Hi @gled-rs 
Still interested in this topic?
If yes, please send me an example SMS of a PagerDuty on-call request.

**Comment by frimtec** [comment]
Just released 2.13.0 with support for dynamic acknowledgment SMS.
The content is extracted with a given regular expression from the received SMS.

To activate set the setting "Acknowledgement method" to "SMS with dynamic text" and define a suitable regular expression.

Would appreciate a short feedback if it works for your use case.

**Comment by gled-rs** [comment]
Wow thank you, I just saw your message, and already got the update. Thanks a ton :)
