### ISSUE TITLE
Numeric shortcode issue

### ISSUE THREAD

**Issue by gled-rs** [frimtec/pikett-assist#585]
Hi,

While testing the dynamic ack, I noticed that upon importing my contact from pagerduty numbers, a few things went wrong:
1/ PagerDuty gives a vcard with all their numbers ( multiple dozen ), and some were not imported ( too many numbers in the list ? )
  => I trimmed it and it seemed to be ok.
2/ PagerDuty mostly uses numeric shortcodes ( example 43105 ) to send alerts, for which you can reply without trouble from the sms client ( no characters used, just numbers ).
  => the numeric shortcodes are not imported in sm2sp. 
  => I then tried to set one of the shortcodes in the "Company" field of the contact, and it imported adding a +1 to the number in sm2p, but Passist still says "Number blocked" in SMS Adapter section of the main screen, and clicking on it, it asks again to add numbers to sm2sp, clicking Allow or Reject does nothing. After that, even though sm2sp shows the list of numbers registered to Passist, and a +1 43105 it extracted from the company field of the contact, receiving a text from that 43105 did nothing.
  
  So I could not test yet the dynamic text :/ 
  
  LMK if you need more infos, happy to help debug that !

**Comment by frimtec** [comment]
Hi,
Yes I guess pure numeric short codes are not supported as they are interpreted as normal numbers and are therefore normalized.
I was not aware that such numbers can be used to send back SMS, in contrast to alphanumeric short codes which do not support it.
Any idea how to detect such numeric short codes?
I have to think about it. Maybe that will take some time as I'm currently quite busy.
Thx for your patience - and for sure, ideas are always welcome.

**Comment by frimtec** [comment]
Just read about short codes in Wikipedia. They are defined differently in each county.
Maybe the library that I use to normalize phone numbers can detect short codes based on the carriers country code from the current used subscription.
If so, a fix should be possible. The fix would be required in s2msp.

**Comment by frimtec** [comment]
Maybe to keep it simple I fill first only support a small list of countries.
You need US, correct?

**Comment by gled-rs** [comment]
I apologize for being not as responsive as I should be, going through a heavy life event at the moment... 

Yes US has shortcodes with 5 or 6 digits long.

**Comment by gled-rs** [comment]
I was able to test a couple times and it works as planned. 

Both dynamic and static confirmation with US shortcodes. Now I have to update the contact, I hope the Company field does not have a short character limit given how many shortcodes Pagerduty advertise as their source :)

Thank you so much @frimtec, PAssist is going to make my life way easier, especially with the current events I am facing..

**Comment by frimtec** [comment]
Many thx for the tests.
Will do the release this weekend.

**Comment by frimtec** [comment]
> I hope the Company field does not have a short character limit given how many shortcodes Pagerduty advertise as their source :)

Now worries, I did another tweak, now you can also define the short code numbers as regular phone numbers in your contact. Just ensure that the numbers have no delimiters. For example `43105` will work, but `431-05` will not.
But you can also keep them in the Company field if you like.

**Comment by frimtec** [comment]
The releases are now done:
* S2MSP: 3.3.0
* PAssist: 2.14.0

Therefore I will close the issue.

If you are happy, please give this github project a ⭐ and/or write a review comment in [Google Play](https://play.google.com/store/apps/details?id=com.github.frimtec.android.pikettassist).
