### ISSUE TITLE
Signal strength supervision configurable for dual SIM phones

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#69]

**Comment by frimtec** [comment]
How to get the telephonyManager for a subscription: https://developer.android.com/reference/android/telephony/TelephonyManager.html#createForSubscriptionId(int)

**Comment by frimtec** [comment]
How to get available subscription list:
https://developer.android.com/reference/android/telephony/SubscriptionManager.html#getActiveSubscriptionInfoList()

final SubscriptionManager subscriptionManager = SubscriptionManager.from(getApplicationContext());
    final List<SubscriptionInfo> activeSubscriptionInfoList = subscriptionManager.getActiveSubscriptionInfoList();
    int simCount = activeSubscriptionInfoList.size();
    btnBack.setText(simCount+" Sim available");
    Log.d("MainActivity: ","simCount:" +simCount);

    for (SubscriptionInfo subscriptionInfo : activeSubscriptionInfoList) {
        Log.d("MainActivity: ","iccId :"+ subscriptionInfo.getIccId()+" , name : "+ subscriptionInfo.getDisplayName());
    }

**Comment by bakito** [comment]
> How to get available subscription list:
> https://developer.android.com/reference/android/telephony/SubscriptionManager.html#getActiveSubscriptionInfoList()
> 
> ```
>     final List<SubscriptionInfo> activeSubscriptionInfoList = subscriptionManager.getActiveSubscriptionInfoList();
>     int simCount = activeSubscriptionInfoList.size();
>     btnBack.setText(simCount+" Sim available");
>     Log.d("MainActivity: ","simCount:" +simCount);
> 
>     for (SubscriptionInfo subscriptionInfo : activeSubscriptionInfoList) {
>         Log.d("MainActivity: ","iccId :"+ subscriptionInfo.getIccId()+" , name : "+ subscriptionInfo.getDisplayName());
>     }```
> ```

Did this not work?
I think it might have been better to use this instead of the current implementation: https://github.com/frimtec/pikett-assist/blob/master/app/src/main/java/com/github/frimtec/android/pikettassist/settings/TelephoneSubscriptionPreference.java#L22

**Comment by frimtec** [comment]
The problem with "getActiveSubscriptionInfoList" is, that it requires the permission "READ_PHONE_STATE" which is on the same criticallity level as the SMS-Permissions :-(

I will look for an other solution.

**Comment by bakito** [comment]
Did you find out, how the subscription id's are numbered.
Do they start with 0 or 1.
On my dual sim the app shows my second one as active. But doesn't allow the first to be selected.

**Comment by frimtec** [comment]
My single SIM phone's subscription has number 1.
I will now adapt the code to always scan all subscriptions from 0-2 and then take all subscriptions that have a valid phone manager.

**Comment by frimtec** [comment]
1.1.6 is online, could you try again?

**Comment by bakito** [comment]
I can select the sim now.
Sim 1 is id 0
Sim 2 is id  1.

Changing the sim does not update the main gui. Needed to kill and restart the app to have it applied.

**Comment by frimtec** [comment]
Thanks for the feedback. Fixing the update issue was easy.
Release 1.1.7 should be online in a few minutes.

**Comment by bakito** [comment]
Works now, thx
