### ISSUE TITLE
Missed SMS on HUAWEI CLT-L29

### ISSUE THREAD

**Issue by frimtec** [frimtec/pikett-assist#79]
Sometimes SMS are missed during sleep mode on the HUAWEI CLT-L29.

**Comment by frimtec** [comment]
Maybe the cause is within the SMS adapter. 
The SMS adapter runs with activated battery optimization. Eventually the SMS adapter is not notified when the phone is in deep sleep mode.

**Comment by frimtec** [comment]
I try to reproduce the issue on my Pixel 2.

**Comment by frimtec** [comment]
I can not reproduce the issue on the Pixel 2.

But I found an interesting article https://stackoverflow.com/questions/36679388/android-sms-receiving-and-handling/36682189:
```
But there's another issue : Deep Sleeping. To preserve battery, Android will turn off any battery-intensive systems when the device is not used for many hours. Battery-intensive systems includes : Wi-fi and Data. SMS is excluded from this list (but some constructors may include an option to disable SMS receptions when in Deep Sleeping, in this case, you have no option, just warn the user to not disable SMS receptions in Deep sleeping), gracefully.
```

@bakito : Can you check if your phone has such an option?
If not, can you try to disable battery optimization for the S2SMP app?

**Comment by bakito** [comment]
Didn't find the sms option. 

Will try with disabling battery optimization for S2SMP

**Comment by frimtec** [comment]
Disabling battery optimization for S2SMP seems to help.
I will enforce this setting with this fix.

**Comment by bakito** [comment]
I can confirm that is now working too on p20 pro (HUAWEI CLT-L29)

Thx a lot
